### ISSUE TITLE
Remove duplice digital service standards

### ISSUE THREAD

**Issue by nokout** [AusDTO/Digital-Service-Standard#2]
There are 4 digital service standards / digital service design guides which I can now see.

https://github.com/AusGovDigital/digital-service-design-guide
https://github.com/AusGovDigital/digital-service-standards
https://github.com/AusDTO/Digital-Service-Standard
https://github.com/AusDTO/DSS-clone

Can we please clean these up or add some information explaining each of their roles.

Related Issues:  https://github.com/AusDTO/DSS-clone/issues/1, https://github.com/AusGovDigital/digital-service-design-guide/issues/2

**Comment by skpandey27** [comment]
AusGovDigital account has been deleted.

**Comment by nokout** [comment]
Thanks @skpandey27 There are still two though, why do we have both https://github.com/AusDTO/Digital-Service-Standard
and https://github.com/AusDTO/DSS-clone?

**Comment by skpandey27** [comment]
Please delete https://github.com/AusDTO/DSS-clone?

**Comment by nokout** [comment]
repository DSS-clone deleted.
