### ISSUE TITLE
Default branch 

### ISSUE THREAD

**Issue by nokout** [AusDTO/Digital-Service-Standard#4]
Hey All, The default branch has been set to "Collaborated-DSS". 
That is why issue #1 is not merging cleanly.

Is there a reason for this or can I change it back?

**Comment by joolswood** [comment]
@skpandey27 ??

**Comment by skpandey27** [comment]
We are still drafting and mirroring content from the website.  Once we have all pages on GitHub, we will push it to Master and Collaborated-DSS will be redundant then.
